#!/bin/bash
# This script downloads gridded data from Smartmet Server (test) for nowcasting purposes
# The script needs a trigger so that it is run whenever the latest LAPS analysis is ready. Currently it is possible that rounded to previous even hour there's no LAPS analysis available. LAPS analysis gets ready around 20 past?

# Input parameters (remember to call shell scripts with named arguments like DATAPATH="/fmi/somepath/" ./run.sh
DATAPATH=${DATAPATH:-"/fmi/data/nowcasting/"}
echo $DATAPATH
DOMAIN=${DOMAIN:-"TULISET2"} # this specifies the extent of the domain which is used
USED_OBS=${USED_OBS:-"laps_skandinavia"}
USED_MODEL=${USED_MODEL:-"pal_skandinavia"}
PREDICTABILITY=${PREDICTABILITY:-"3"} # This must be an even number as model data is not available on a more frequent temporal resolution

# Generate current timestamps for the Smartmet Server retrievals. Here, 3hours can be taken in as an argument (defined maybe by the radar nowcasting predictability parameter?). The retrieval time stamps are rounded to previous hour.
timestamp_now=`eval date -u -d "now" +"%Y%m%d%H"`00
timestamp_fcst=$(eval 'date -u -d "now + $PREDICTABILITY hour" +"%Y%m%d%H"')00
timestamp_m4hours=$(eval 'date -u -d "now - 4 hour" +"%Y%m%d%H"'00)
echo $timestamp_now
echo $timestamp_fcst
echo $timestamp_m4hours


#MINS_BETWEEN_STEPS=${MINS_BETWEEN_STEPS:-15}
#INPUT1=${INPUT1:-"201608151215_radar.rack.comp_CONF=TULISET2.h5"}
#INPUT2=${INPUT2:-"201608151230_radar.rack.comp_CONF=TULISET2.h5"}
#METHOD=${METHOD:-"proesmans"}
#OUTDIR=${OUTDIR:-"/fmi/dev/run/nowcasting/testdata/"}
#OUTFILE=${OUTFILE:-"201608151230_spoflow.proesmans_ravake.h5"}





#for parameters in Pressure, GeopHeight, Temperature, DewPoint, Humidity, Visibility, PressureAtStationLevel, WindSpeedMS, WindDirection, WindVectorMS, HourlyMaximumGust, WindUMS, WindVMS, SurfaceWaterPhase #these parameters are available for the producer laps_skandinavia
for parameter in Pressure Temperature
do


OBSDATA="$timestamp_now"_"$USED_OBS"_DOMAIN="$DOMAIN"_"$parameter".nc
MODELDATA="$timestamp_now"_fcst"$timestamp_fcst"_"$USED_MODEL"_DOMAIN="$DOMAIN"_"$parameter".nc
echo $OBSDATA
echo $MODELDATA

# : <<'END'

# Working retrieval to ECMWF-data generated by Marko
#wget -O out2.nc --no-proxy 'smartmet.fmi.fi/download?param=Temperature&producer=ecmwf_eurooppa_pinta&format=netcdf&bbox=19.1,59.7,31.7,70.1&timesteps=24&projection=epsg:4326'


# Retrieving LAPS data over Scandinavian domain
query="wget -O "$DATAPATH$OBSDATA" --no-proxy 'http://smartmet.fmi.fi/download?param="$parameter"&producer=laps_skandinavia&format=netcdf&origintime="$timestamp_now"&bbox=4.00118791,50.00007491,42.99146951,72.99231333&projection=epsg:4326'"
echo $query
eval $query

# IF NO LAPS AVAILABLE THEN WHAT?!

 

# Retrieving pal forecast over Scandinavian domain
query="wget -O "$DATAPATH$MODELDATA" --no-proxy 'http://smartmet.fmi.fi/download?param="$parameter"&producer=pal_skandinavia&format=netcdf&starttime="$timestamp_fcst"&bbox=4.00118791,50.00007491,42.99146951,72.99231333&projection=epsg:4326'"
echo $query
eval $query

#wget -O latest_pal.nc --no-proxy 'smartmet.fmi.fi/download?param=Temperature&producer=pal_skandinavia&format=netcdf&bbox=4.00118791,50.00007491,42.99146951,72.99231333&timesteps=3&projection=epsg:4326'



# this is not working really
# gdalwarp -t_srs epsg:3067 -of netCDF 201805311000_fcst201805311300_pal_skandinavia_DOMAIN\=TULISET2_Pressure.nc output.nc


# While retrieving data from Smartmet Server, projection 3067 does not work at the moment. Also, datas are coming with full resolution which might not be the most appropriate thing to do. If there's an option to use a common resolution for all data sources that could be used. Otherwise, interpolation will need to be done after the retrieval.

# END

# produce optical flow based interpolation...

# remove original input files
query="rm "$DATAPATH$OBSDATA
echo $query
eval $query
query="rm "$DATAPATH$MODELDATA
echo $query
eval $query
 
done


exit
