#!/bin/bash
#Run interpolation for case

#Case parameters
DATAPATH="/radar/storage/HDF5/interpolation/HDF5/20150626/"
TIMESTAMP_FIRST="201506261130"
TIMESTAMP_LAST="201506261230"
MINS_BETWEEN_COMPOSITES=5
DOMAIN="fmi.radar.composite.lowest_FIN_RAVAKEBIG"

#Interpolation parameters
OUTPATH=$DATAPATH
OUTFILE_INTERP="{}_${DOMAIN}.h5"
OUTFILE_SUM="{}_5minsum_${DOMAIN}.h5"
SECONDS_BETWEEN_STEPS=30

#Loop over files
TIMESTAMP=$TIMESTAMP_FIRST
DATE=${TIMESTAMP:0:8}' '${TIMESTAMP:8:2}:${TIMESTAMP:10:2}
NEXT_TIMESTAMP=$(date -d "$DATE $MINS_BETWEEN_COMPOSITES min" +%Y%m%d%H%M)

while [ $NEXT_TIMESTAMP -lt $TIMESTAMP_LAST ];do

    DATE=${TIMESTAMP:0:8}' '${TIMESTAMP:8:2}:${TIMESTAMP:10:2}
    NEXT_TIMESTAMP=$(date -d "$DATE $MINS_BETWEEN_COMPOSITES min" +%Y%m%d%H%M)

    IMAGE1="${TIMESTAMP}_${DOMAIN}.h5"
    IMAGE2="${NEXT_TIMESTAMP}_${DOMAIN}.h5"

    #Call interpolation
    cmd="DATAPATH=$DATAPATH IMAGE1=$IMAGE1 IMAGE2=$IMAGE2 SECONDS_BETWEEN_STEPS=$SECONDS_BETWEEN_STEPS OUTPATH=$OUTPATH OUTFILE_INTERP=$OUTFILE_INTERP OUTFILE_SUM=$OUTFILE_SUM ./generate.sh"
    echo $cmd
    eval $cmd
 
    TIMESTAMP=$NEXT_TIMESTAMP

done

